# Generated by Django 5.0.6 on 2024-07-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='doctor_id',
            field=models.IntegerField(),
        ),
    ]
