# Generated by Django 5.0.6 on 2024-07-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_medicalprescription_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprescription',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
